[package]
name = "rust_full"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "Projects/crate_01_test",
    "Projects/crate_02_variables", 
    "Projects/crate_03_conditional_and_loops", "Projects/crate_04_functions", "Projects/crate_05_memory_mgmt",
    
]

[dependencies]
